### ISSUE TITLE
gsutil ignores trickle

### ISSUE THREAD

**Issue by ChristianBachla** [GoogleCloudPlatform/gsutil#1092]
According to the [link](https://cloud.google.com/storage/docs/gsutil/addlhelp/Throttlinggsutil) it should be pretty simple to upload a file to a bucket, while limiting the bandwidth, using trickle. I have tried with different types of files, on two different machines (amd64 and arm64, both running Ubuntu 18.04). 

If i set the upload and download speed to be 100 KB/s and the file is 256 MB, it is uploaded in approximately 10 seconds. According to my calculations, it would take "a bit" longer if trickle had any influence over gsutil. 

I installed trickle and gsutil 3 days ago, and i have followed the installation instructions, provided by the google cloud documentation.  

If anyone might have an answer to my problem, it would be nice.

**Comment by ChristianBachla** [comment]
The copy-paste paste error is not the source of my upload problem. Wish it were though.

**Comment by starsandskies** [comment]
Darn, unfortunately that's about the limit to how useful I'm going to be on this issue :-/

**Comment by i-am-gizm0** [comment]
`trickle` still doesn't seem to have any effect on `gsutil` a year and a bit later

**Comment by ning-y** [comment]
It seems Google is aware that trickle does not work with gsutil: OP's link https://cloud.google.com/storage/docs/gsutil/addlhelp/Throttlinggsutil now redirects to https://cloud.google.com/storage/docs/gsutil/addlhelp/GlobalCommandLineOptions, which has no mention of trickle. The only recommended option for throttling now is to disable any form of concurrency, and limit disk read/write using ionice.

I don't know about you, but this is not sufficient for my purposes. The machine I work on has a cheap USB WiFi adapter which would fail when it encounters high bandwidths, and the only way to rescue the adapter is to unplug and plug it back in. I work remotely from said machine, so it is really important that I am able to throttle gsutil's bandwidth. Otherwise, with the current no-concurrency+ionice "solution", the bandwidth usage still crashes the WiFi adapter, and I have to be around to manually plug/unplug the adapter.

AWS S3 can be throttled using a single configuration command ([see this StackOverflow answer](https://stackoverflow.com/a/49647957/6910451)). GSUtil's failure to throttle was first reported **six years ago** in March 2016 on [StackOverflow](https://stackoverflow.com/questions/35904457/gsutil-rsync-is-killing-my-cable-modem-looking-for-command-line-throttling). It would be really nice if the GSUtil team would consider implementing a more explicit throttling feature than no-concurrency+ionice.

**Comment by starsandskies** [comment]
I'm afraid I won't be all that helpful, but to provide full transparency, yes, the Throttlinggsutil page was removed because trickle was the main reason the page existed, and since trickle didn't seem to work, there wasn't a lot of reason to keeping the page around. Here's the PR that removed the source for the Throttlinggsutil page: https://github.com/GoogleCloudPlatform/gsutil/pull/1134
