### ISSUE TITLE
gsutil app uses plain gmail support email, no privacy policy linked

### ISSUE THREAD

**Issue by mlazowik** [GoogleCloudPlatform/gsutil#1223]
When auditing apps used in our Workspace we noticed that gsutil (app id `909320924072.apps.googleusercontent.com`) specifies `gsutil.oauth2@gmail.com` as the support email, and does not link to any privacy policy.

From brief research it does seem to be the official gsutil app, but the gmail address does inspire much confidence and it's not easy to tell if it's some rogue app pretending to be gsutil. IMO it would be better if it specified a @google.com address (I hope those support addresses are verified?).

**Comment by thomasmaclean** [comment]
This is an artifact of how oauth2 was set up for GSUtil. Although in retrospect I agree the use of a Gmail account was less than ideal, it's how the client has been set up and will likely remain this way in perpetuity so as not to interrupt the authorization flow going forward. FWIW Cloud SDK uses a different client_id, which is generally more common since GSUtil is usually installed alongside the SDK.

**Comment by mlazowik** [comment]
Hm, I was able to change the support email in one of our internal apps to a group managed by me without affecting any existing usages.

**Comment by thomasmaclean** [comment]
Thanks for pointing that out. It looks like my understanding of how was set up was incomplete. We've had other complaints about this as well, so I'll look to prioritize a fix for this next week.

**Comment by thomasmaclean** [comment]
I went ahead and updated the contact email to be gsutil-oauth2@google.com. Thanks again for letting us know!

**Comment by mlazowik** [comment]
Thank you!
