### ISSUE TITLE
gsutil rsync not working in version 4.63

### ISSUE THREAD

**Issue by Byte27** [GoogleCloudPlatform/gsutil#1292]
In version 4.62 the command works fine, but in version 4.63 the following command starts giving errors:

```
gsutil -m rsync -r gs://my-bucket/directory/static /var/www/html
```

Error returned:

```
Building synchronization state...
Starting synchronization...
Copying <file>..
Skipping attempt to download to filename ending with slash
(/var/www/html/). This typically happens when using gsutil to download
from a subdirectory created by the Cloud Console
(https://cloud.google.com/console)
InvalidUrlError: Invalid destination path: /var/www/html/
Copying <file>...
CommandException: 1 files/objects could not be copied/removed.
```

**Comment by dilipped** [comment]
Thanks for reporting! How many objects do you have under `gs://my-bucket/directory/static`? Do you get the "Skipping attempt" message even with 4.62?

**Comment by Byte27** [comment]
Maybe 50 to a 100 objects. I don't believe we get the Skipping attempt message with 4.62

**Comment by dilipped** [comment]
That's very strange that you are not seeing the "Skipping attempt" line for 4.62. The only thing that has changed between 4.62 and 4.63 is that we now raise an error if the destination is invalid instead of simply skipping it. This is an intended behavior in 4.63. I am guessing you have an **object** that ends with a slash and because we can't create a file with a slash at the destination, we raise an error. This error should not block other valid objects from being copied. I am guessing that other objects have been copied correctly for you. I would recommend renaming your object that is ending with a slash to a valid name. You can try doing `gsutil ls -r gs://my-bucket/directory/static` and see if you get a listing that says `gs://my-bucket/directory/static/` to find our the object ending with slash.

**Comment by Byte27** [comment]
Looks like we indeed had an object with a slash in there. Thanks!
