### ISSUE TITLE
parallel_process_count=1 and parallel_thread_count=1  don't work as expected

### ISSUE THREAD

**Issue by bduclaux** [GoogleCloudPlatform/gsutil#1409]
Hello

I am using gsutil version 5.3 on debian, inside a GKE cluster.
To reduce memory/cpu usage during Kubernetes pod initialization, we use parallel_process_count=1 and parallel_thread_count=1 options.
However, some initContainers get OOM Killed, because the python3 process uses too much memory.
While investigating the problem, it appears that the options parallel_process_count=1 and parallel_thread_count=1 actually create two python3 child processes, which should not happen according to the docs. There should be only one process.

Here is a trace of 'ps auxf' doing a simple gsutil cp using the above options:
```
5398 pts/1    S+     0:00      \_ python3 /usr/local/bin/gsutil -o GSUtil:parallel_thread_count=1 -o GSUtil:parallel_process_count=1 cp -r gs://xxx /tmp/dummy
 5399 pts/1    Sl+    0:00          \_ python3 /usr/local/bin/gsutil -o GSUtil:parallel_thread_count=1 -o GSUtil:parallel_process_count=1 cp -r gs://xxx /tmp/dummy
 5401 pts/1    Sl+    0:00          \_ python3 /usr/local/bin/gsutil -o GSUtil:parallel_thread_count=1 -o GSUtil:parallel_process_count=1 cp -r gs://xxx /tmp/dummy

```

The gsutil command create 3 processes in total (the main one, and 2 child ones), instead of one, and so the total memory used to run the gsutil command is actually 3x, which creates memory pressure on GKE, and ultimately leads to OOMKills.

Thanks

**Comment by dilipped** [comment]
The child processes that you see there are expected even for non-parallel behavior. We you run gsutil via Cloud SDK, there are wrapper scripts involved which will delegate the task to a child process, because of which you see the process tree above. But eventually, the work is getting done only by a single process (5401 in the above case). The process 5398 and 5399 above are not performing any work. They are just waiting for the child to finish. So in reality, they are not consuming any additional memory.

If parallel processing was turned on, you would have seen more processes under 5401.
