### ISSUE TITLE
gsutil rsync ouput is incorrectly written to stderr instead of stdout

### ISSUE THREAD

**Issue by simonvanderveldt** [GoogleCloudPlatform/gsutil#1410]
When running `gsutil rsync` its output 
```
Building synchronization state...
Starting synchronization...
Copying gs://<something>
/ [0/1 files][    0.0 B/  6.2 KiB]   0% Done                                    
/ [1/1 files][  6.2 KiB/  6.2 KiB] 100% Done
Operation completed over 1 objects/6.2 KiB.
```
is written to `stderr` instead of `stdout`
Since these are all normal messages and not errors these should all go to `stdout`.

**Comment by dilipped** [comment]
This is intended behavior. The output from rsync is for progress reporting purposes only, and it's a common practice across different tools to use stderr for progress reporting.

**Comment by simonvanderveldt** [comment]
@dilipped OK, thanks for the information.
It might be intended behavior, but that seems like a wrong design decision, it flies in the face of how everything (on Linux/UNIX like systems) works and what other applications/systems expect. It makes life unnecessarily hard for those that have to process these logs.

A nice example are Google's own tools like Logging in GCP which is showing all the logs coming from `gsutil rsync` as `ERROR` (because they are sent to `stderr` of course) which creates so much noise that it's impossible to find any actual problems, which makes the logging useless.

I don't know why or how this design decision was made, but can that decision be revisited?

**Comment by dilipped** [comment]
This is definitely one of the long debated topics in the developer community :-) : https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout

I am not sure why the decision was made to send the progress reporting to stderr, but if I have to guess, I would say that it's because these logs are meant for information and diagnostic purpose only. A `Copying gs://<something>` message does not guarantee that the file will be successfully copied. So any tooling should not be dependent on it anyway.

Now I can see that some tools do write such statuses to `stdout` e.g `rsync -v` on Unix. But I can also see other tools like `git clone ...` which writes each progress to stderr. So I don't think there is a standard convention.

BTW, you can always use the `-q` flag, if you only care about the error messages and don't want the progress information.
