### ISSUE TITLE
Issue while running gsutil in unix

### ISSUE THREAD

**Issue by roshniphilip** [GoogleCloudPlatform/gsutil#156]
Hi,
I encountered the following error while running the command 'gsutil' in unix:

[rphiliip@eginformatica01d ~]$ gsutil
  File "/home/rphiliip/gsutil/gsutil", line 79
    local_crcmod_path = CRCMOD_OSX_PATH if IS_OSX else CRCMOD_PATH
                                         ^
SyntaxError: invalid syntax

Please provide your inputs.Downloaded the latest version from this site after trying with the copy in google docs link.

**Comment by almgwary** [comment]
this wasting of time bug still exist, this wasting of time

**Comment by almgwary** [comment]
Warning: On some Linux distributions, another tool named gsutil, by GrandStream BudgeTone, is pre-installed. If you run this command instead of the Google Cloud Storage gsutil, it will likely print an error message similar to "Choose one of -b, -d, -e, or -r to do something". If this happens, you can either move the Google Cloud Storage version of gsutil to the front of your PATH environment variable, or you can specify the full path when running Cloud Storage gsutil (for example, /home/users/joan/gsutil/gsutil ls).

**Comment by almgwary** [comment]
there is already linux package installed before with same name, which made this confilct.

you can follow this Google docs, it solved my problem .

https://cloud.google.com/sdk/auth_success
