### ISSUE TITLE
gsutil cp from STDIN fails with large files

### ISSUE THREAD

**Issue by slundberg** [GoogleCloudPlatform/gsutil#229]
I was using gsutil to stream genomic data processing results and found that any job with a large file (2-5GB) failed. Inside map reduce the original error was `Failure: size does not fit in an int.` which is probably related to #200, except now the file is coming over STDIN.

If case it is helpful I get a similar error `Failure: length too large.` when trying to upload a file directly from my machine over STDIN. But do not get an error if I specify the filename.

I am running `gsutil version: 4.6`

**Comment by ryan-williams** [comment]
Just had this fail/abort after apparently transferring a whole 10GB file:

```bash
$ gsutil cp <(curl -L $URL) gs://$BUCKET/
Copying file:///dev/fd/63 [Content-Type=application/octet-stream]...
100  9.9G  100  9.9G    0     0  55.1M      0  0:03:03  0:03:03 --:--:-- 58.7M
Failure: length too large.
```

The transfer proceeded normally all the way to `curl` reporting 100% before something in the `gsutil` stack threw an error.

The `$URL` in question is a dropbox.com file that I would like to transfer to google cloud storage as directly as possible. Can anyone recommend a way to do this?

Confused by this issue being closed if the `gsutil` CLI is not fixed, which is my reading of the previous comment.

**Comment by houglum** [comment]
Thanks for the report. I can reproduce this 100% of the time with gsutil 4.25.

It looks like we decide to use the SIMPLE_UPLOAD upload strategy, rather than the RESUMABLE_UPLOAD strategy, when the input comes from process substitution.

- We assume that inputs in the form a stream will be piped in, and users will use "-" as the first argument to cp to indicate this.
- Because we can't determine that the "file" size is going to be greater than the resumable upload threshold when we start the copy operation, gsutil chooses SIMPLE_UPLOAD rather than RESUMABLE_UPLOAD.

As such, you should pipe the input to gsutil explicitly (and I also recommend using the -m flag if uploading a 10GB file):

    curl -L URL | gsutil -m cp - gs://$BUCKET/

And another option: you could also take a look at transferring large files via the [GCS transfer service](https://cloud.google.com/storage/transfer/) if you have lots of files and know the URLs ahead of time.

**Comment by ccjon** [comment]
fwiw, 
gsutil version: 5.6

 CommandException: Cannot upload from a stream when using gsutil -m option.
