### ISSUE TITLE
depot_tools and gsutil do not respect proxy settings

### ISSUE THREAD

**Issue by rakuco** [GoogleCloudPlatform/gsutil#241]
This is an attempt at better summarizing the issue #240 is trying to solve as well as how [Chromium bug 443523](http://crbug.com/443523) is related to gsutil. I'm assuming everybody is familiar with [depot_tools](http://dev.chromium.org/developers/how-tos/depottools).

One of the scripts in depot_tools is **download_from_google_storage**, which is primarily used to download binaries (GN, clang-format, binutils) from Google Storage (behind the scenes, it is basically a  wrapper around `gsutil ls`, `gsutil cp` etc). Those binaries all in public buckets, so fetching them does not require authentication.

When download_from_google_storage is passed the "--no_auth" option (as is the case when fetching those public binaries as part of Chromium's runhooks stage), it sets the `BOTO_CONFIG` environment variable to `""` so that any existing Boto authentication settings are not used.

This used to work fine for everyone while depot_tools kept its own copy of an old gsutil version with some patches on top. Recently, it switched to a vanilla copy of gsutil 4.7, and this caused download_from_google_storage to stop working for people behind proxies:
1. download_from_google_storage is invoked with "--no_auth"
2. It empties the `BOTO_CONFIG` environment variable
3. It calls `gsutil ls`, then `gslib/gcs_json_api.py` calls `gslib.util.GetNewHttp()`
4. `GetNewHttp()` reads proxy settings from Boto
5. The HTTP calls in `gsutil ls` all time out because the proxy settings are incorrect

The problem can be addressed from at least two different angles:
* download_from_google_storage could stop resetting `BOTO_CONFIG`, but that would both cause problems for people with proper `.boto` files (possibly, I'm not very familiar with Google Storage and why Chromium tries to avoid Boto) as well as require everyone behind a proxy to have their proxy settings in a `.boto` file -- doable, but likely to cause confusion, and I am not sure Chromium's infra team wants to go in this direction.
* Stop only retrieving proxy settings from Boto and falling back to environment variables if the first approach fails (as #240 does). This is also related to #171, which originally came from a depot_tools patch -- if we are to read the proxy settings from the environment, we'd better not unset `http_proxy` (#240 without #171 works because several connections are made via HTTPS so `https_proxy` is read instead). This option causes less trouble for Chromium, but might be against gsutil's philosophy of always relying on Boto for proxy settings.

**Comment by rakuco** [comment]
+@thobrla, @primiano, @aarongable, @vapier

**Comment by thobrla** [comment]
It's unclear from the description whether:
1. There were valid proxy settings in the .boto configuration file that were then cleared by resetting the BOTO_CONFIG variable
2. The custom-patched version of gsutil that depot_tools had modifications that got the proxy information from the environment.

Regardless, as far as gsutil goes, this is really a feature request for gsutil to support the "http_proxy" and "https_proxy" environment variables.

As mfschwartz noted in https://github.com/GoogleCloudPlatform/gsutil/pull/171, this causes problems with boto, so I don't think it's realistic to support it for the XML codepath.  However, we could support it for the JSON codepath, which is the default.  There are two main disadvantages that I can see.  First, it would mean divergent behavior in the XML and JSON codepaths.  Second, it would create a divergent configuration space where proxy settings could be configured either via .boto or the environment, which would make debugging proxy issues more difficult.

Given that this environment variable is honored by wget and curl, I'm inclined to implement this for the JSON codepath despite the disadvantages.

An alternative would be for download_from_google_storage to properly set the configuration in a temporary boto file or pass the proxy configuration down via top-level -o options to gsutil.

**Comment by rakuco** [comment]
> It's unclear from the description whether:
> 1. There were valid proxy settings in the .boto configuration file that were then cleared by resetting the BOTO_CONFIG variable

There could have been, though Chromium never required any user to have a .boto file so it's always been ignored.

> 2. The custom-patched version of gsutil that depot_tools had modifications that got the proxy information from the environment.

AFAICS [the old gsutil version depot_tools used, 3.25,](https://chromium.googlesource.com/chromium/tools/depot_tools/+/master/third_party/gsutil/) only had one change related to this, which is #171. The code there did not have `gslib.utils.GetNewHttp()` or `gcs_json_api.py` at all, so I'm guessing the environment variables were being used just because nothing was preventing them from being used.

As for the rest, I guess it would be good if Chromium's infra team chimed in.

**Comment by vapier** [comment]
in the CrOS case, there are no proxy settings in the .boto config.  the depot_tools patch is basically what is posted in my pull request.

XML/JSON behaviors are already diverging and any bugs reported about the XML code path largely get rejected/sat upon and told to "use JSON instead".  so i don't see why we need to hold this fix against that.

wrt runtime behavior, i don't see the problem.  proxy env vars don't randomly show up ... users explicitly put them there because they're trying to configure system wide proxy settings.  i'm not sure why this would make debugging difficult -- if you've got debugging statements in there already to dump things, then add one for http_proxy/https_proxy.

**Comment by rakuco** [comment]
For the record, @thobrla has sent https://codereview.appspot.com/192920043/ but not everyone here's been CC'ed there (and I got CC'ed with my personal email address :)

**Comment by thobrla** [comment]
After talking with mfschwartz, instead of submitting that change, we want to extend it to also support XML provided we don't encounter major compatibility issues.  However, this will take a bit longer to implement and test.

In the meantime, you can use the -o option to pass proxy configuration to gsutil on the command line, without using the BOTO_CONFIG variable, for example:
gsutil -o 'Boto:proxy=192.168.1.1' -o 'Boto:proxy_port=12345' cp ...

**Comment by rakuco** [comment]
That's good to hear, though the suggested workaround doesn't really work for depot_tools since users don't call `gsutil` directly. Unless the infra team is OK with adding some code to parse proxy settings and pass them in the command-line for a while, I guess...

**Comment by thobrla** [comment]
Proxies are supported in gsutil via boto configuration only, and this has been the case for a long time; parsing proxy settings and passing them in a supported fashion is a big step forward from using a custom (and quite dated) version of gsutil.

**Comment by vapier** [comment]
keep in mind that while Chromium has an older (and patched) version in depot_tools, it is not the version that Chromium OS uses in general.  CrOS uses the latest (4.7) and does not patch it.  we too want gsutil to respect the standard proxy settings since users already utilize them.

having every gsutil caller parse the env vars and try to turn them into the -o options for gsutil doesn't scale that well ;)

**Comment by rakuco** [comment]
To be fair, Chromium does not have an older (and patched) version in depot_tools anymore and has the same issue as CrOS (if I understood you correctly) -- in fact, that's what prompted this issue and my pull request.

**Comment by vapier** [comment]
depot_tools/third_party/gsutil/ looks like it's still using gsutil 3.25 to me

https://chromium.googlesource.com/chromium/tools/depot_tools/+log/master/third_party/gsutil

**Comment by rakuco** [comment]
See [this depot_tools commit](https://chromium.googlesource.com/chromium/tools/depot_tools/+/199bc5f92c0dabcb7cbdd9c7c37f4a951dbd56ea), and [prior ones with more background](https://chromium.googlesource.com/chromium/tools/depot_tools/+/7a79054e2fa2d08ce3b1711aa302737a803feb12).

The copy in third_party/gsutil is being phased out, and download_from_google_storage and friends which I mentioned in the issue report are already using 4.7.

**Comment by edsut** [comment]
I've been trying to get "fetch webrtc" to work for several days, and now thanks to this initial post, I've got it.  So I figured I'd comment...
I was trying to follow the instructions (http://www.webrtc.org/native-code/development) to download webrtc native code.  I had configured both git and svn to deal with the fact that I am behind a proxy; plus I installed all the prerequisite software (including depot_tools) as outlined there.
After running "fetch webrtc", it would run for about an hour, then spit out an error (see https://groups.google.com/forum/#!topic/discuss-webrtc/Dt-GRIlLVe4 if interested).
I then attempted to do the same thing on a machine outside my firewall and it worked; so I was able to conclude that it had something to do with the firewall.
Eventually I stumbled on the .boto file, so I created it and added the necessary proxy information, but it didn't help.  Then after reading this post, I modified download_from_google_storage.py in my depot_tools directory so that it would ignore the --no_auth option.  That finally allowed me do successfully run "fetch webrtc" through a proxy. 
So, is this an issue with depot_tools or am I just totally doing something wrong?

**Comment by thobrla** [comment]
gsutil will support proxy configuration via the environment in 4.8 per https://github.com/GoogleCloudPlatform/gsutil/commit/b1ece8cf0da1e9e4d05f12a58ff40f8f98548a7d

If proxy configuration is not present in the .boto configuration file, gsutil will fall back to environment variables http_proxy, https_proxy, HTTPS_PROXY in that order.  Note that only a single environment variable is support for configuration - there is no support for using one proxy for http and a separate proxy for https.

**Comment by MatrixMuto** [comment]
does gsutil support socks5 proxy?

**Comment by thobrla** [comment]
Not presently, HTTP proxies only.

**Comment by MatrixMuto** [comment]
I'm not famliar with python, just solve my proxy issue via hard code. 
if set proxy via env,it should use 
"https_proxy=socks5://127.0.0.1" 
or "sock5_proxy=socks5://127.0.0.1"
does it should be implement in the httplib2? 
```python
def proxy_info_from_url(url, method='http'):
```

**Comment by thobrla** [comment]
We could add support - feel free to open a separate issue for that; you could even [author the code](https://cloud.google.com/storage/docs/gsutil/addlhelp/ContributingCodetogsutil) if you'd like some practice with Python.
