### ISSUE TITLE
gsutil cp between gs:// URLs doesn't respect -h

### ISSUE THREAD

**Issue by dborowitz** [GoogleCloudPlatform/gsutil#246]
gsutil rm gs://bucket/bar; gsutil -h 'Content-Disposition:attachment; filename=baz' cp gs://bucket/foo gs://bucket/bar && gsutil ls -L gs://bucket/bar
Removing gs://bucket/bar...
GSResponseError: status=404, code=NoSuchKey, reason=Not Found.
Copying gs://bucket/foo...
gs://bucket/bar:
        Creation time:  Wed, 07 Jan 2015 23:09:33 GMT
        Cache-Control:  private, max-age=0
        Content-Disposition:    attachment
        Content-Language:       en
        Content-Length: 129975097
        Content-Type:   application/octet-stream
        ETag:           *
        ACL:            *
TOTAL: 1 objects, 129975097 bytes (123.95 MB)

Where did my filename go?

Running gsutil setmeta on bar directly works.

**Comment by thobrla** [comment]
I took a look, and gsutil is actually doing the right thing; this is an issue with the Google Cloud Storage XML API not honoring the content-disposition header with x-goog-metadata-directive: COPY.  It does honor the header for x-goog-metadata-directive: REPLACE, which is why the setmeta command works.

Since I'm not sure how soon it will be fixed in the service, as a workaround you can use the (gsutil default) JSON API by not setting prefer_api=xml in your .boto file.
