### ISSUE TITLE
1. Uploading... 2. Failed... 3. File nonetheless uploaded

### ISSUE THREAD

**Issue by karalabe** [GoogleCloudPlatform/gsutil#249]
Hi all,

I'm using gsutil to upload some files to GCS and I'm hitting an annoying bug. [Background: since the official Go client libraries to access Google Storage are currently buggy beyond use, I've created a small wrapper around gsutil that simply streams data into its stdin, and delegates uploading to it]. The wrapper works beautifully, I've managed to successfully (and consistently) upload files of around 30GB.

Today however I've had a slightly different use case, where I've started an upload, but only sent data trickling through stdin (a data processing program is churning out the results slowly and sending it to gsutil to upload to GCS). The phenomenon I see is that after finishing the long running processing task (~1h) and sending a few hundred kilobytes go gsutil, I close stdin, and gsutil starts uploading the data:

```
Copying from <STDIN>...
Uploading   ...: 65.8 KiB    
Uploading   ...: 137.8 KiB    
Uploading   ...: 209.8 KiB    
Uploading   ...: 64.6 KiB    
Uploading   ...: 136.6 KiB    
Uploading   ...: 208.6 KiB    
Failure: must be string or buffer, not None.
```

Now, there is one odd thing and one annoying thing:

 - Looking at the above output, I see that the upload is restarted. I'm guessing that gsutil fetched an OAuth token when the stream started, but by the time I've finished it expired, so the first upload trial failed and it had to try again (just a hunch, I can live with this).
 - gsutil then fails, returning both the above error message, as well as terminating with a non zero status code. My code considers the upload failed, however, looking at the bucket contents, the upload actually succeeded.

So in essence, gsutil reports failure on all possible channels, yet succeeds the operation. This is really annoying because now I have actually no means to know whether the op succeeded or not. Could it be that the failure belongs to the first trial and then gsutil actually succeeded? But then why report the failure?

Ideas? :)

Thanks,
  Peter

PS: Note, if I'm streaming massive amount of data, then even very long running uploads (4-6 hours) succeed ok, yet if I only trickle data in a longer time window, then everything blows up.

PPS: gsutil version: 4.7, latest according to the gcloud updater

**Comment by thobrla** [comment]
Thank you very much for the detailed bug report.  I'll work on reproducing this locally, but in the meantime, can you run your command with the debug flag to collect a stack trace:

your-data-processing-script | gsutil -D cp - gs://your-bucket/your-object

This should hopefully help get to the bottom of the "must be string or buffer" exception.

There are a number of possibilities that could cause a retry, and starting in gsutil 4.7 we buffer up to 100MB of a stream of data in case there are any transient errors on the service side.  This is a likely explanation for why the upload appears to restart.

I suspect that the object was successfully uploaded, and then later line of code raised the exception, which is why you get a nonzero exit code but still see the object in the bucket.

PS: gsutil 4.8 should be out on gcloud shortly (tomorrow is likely); I don't expect it will solve this problem, but it's worth updating to just to be on the same page.

**Comment by thobrla** [comment]
Update: I was able to reproduce this locally, so no need to send the gsutil -D trace.

Furthermore, the object I streamed was created successfully and I verified that all of the contents were correct - I suspect the same is true for your case.  I believe the issue is improper handling of sending the last "0" bytes of a stream after an access token refresh causes the entire (short-length) stream to be retried because the server didn't get enough data to commit before the access token expired.

I'm working on a fix for gsutil 4.9.

**Comment by thobrla** [comment]
This is fixed for 4.9 with https://github.com/GoogleCloudPlatform/gsutil/commit/912e52c6031b1bf8fe62dda220d90d8aacb19745

If you'd like to pick up the fix sooner, you can run the following:

For gcloud installs:
  `gcloud components repositories add https://storage.googleapis.com/prerelease/cloudsdk-prerelease-components/gsutil_4.9pre_trickleupload/components-2.json`
  `gcloud components update`

For standalone installs:
  `gsutil update gs://prerelease/gsutil_4.9pre_trickleupload.tar.gz`

**Comment by karalabe** [comment]
Thanks for the fix! Sorry I couldn't reply earlier, was busy with other aspects of my system. Any ideas on when this release will hit CGE? I'm running gsutil inside a GCE instance with the stock gsutil, so it would be nice if I didn't have to bundle a custom binary.

**Comment by thobrla** [comment]
4.9 is released now, so depending on your GCE image you could run 'gcloud components update -q'
