### ISSUE TITLE
Request: convert to Java code (and to Android's library)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [GoogleCloudPlatform/gsutil#257]
Advantages of converting to Java:
-more people use JRE than Python runtime
-more developers use Java than Python.
-easier to use
-could probably be converted easily to be a library for Android.

Disadvantages:
-takes time?

**Comment by mfschwartz** [comment]
Hi,

We aren't going to convert gsutil to Java, for several reasons:

1. It would be a huge amount of work - gsutil plus all of it's libraries represents years of development.

2. gsutil is provided only as a tool -- the underlying code is not being exposed as an SDK (see https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/README).

3. We developed gsutil in Python in the first place because the Java runtime takes too long to start to use it as a basis for building a command line tool.

Mike

**Comment by AndroidDeveloperLB** [comment]
1. Too bad. As nice as Python is in terms of syntax (though I'm not a Python developer, I do think it look nice), I still think that Java would be a better thing to use, just because of its popularity and how close it is to Android.

2. You mean a part of it is closed source, which means only a part of it can even be converted to Java?
Can't you at least expose only the basic stuff? To have a starting step that others can continue, and make all the features that you have?

3. Python runtime is faster than Java runtime ? I thought it's the opposite (I've read statistics and benchmarks about this)... But how long could it take anyway, seeing that most of the time is probably for the internet connection ?

4. Are there any alternatives?
It could really be nice to have a tool on Android itself, to see some dashboard statistics on Android devices...

**Comment by mfschwartz** [comment]
Hi the gsutil library code is not closed source; rather, it's a product decision not to expose a "gsutil SDK".

**Comment by AndroidDeveloperLB** [comment]
so if one component isn't exposed to show its code, why can't it be considered semi-open-source?
Suppose I have the whole time I need (and/or people), I don't think it would be practical to convert the code to Java and make it work, if some components of it (especially the "engine") aren't exposed to me.

**Comment by Capstan** [comment]
re: 3, the problem for a command-line tool isn't execution speed but startup speed. The Java runtime takes a while to launch.

What are the gsutil features you're wanting to have access to in Java? Any of them must haves? 

You may be able to get some or all of what you want via the [Google APIs Client Library for Java](https://github.com/google/google-api-java-client), specifically the classes for [Google Cloud Storage](https://developers.google.com/api-client-library/java/apis/storage/v1). One note is that [our Java sample](http://samples.google-api-java-client.googlecode.com/hg/storage-cmdline-sample/instructions.html "Instructions for the Cloud Storage JSON Command-Line Sample") does not currently show how to do Android-style authentication; you'll have to crib from the [Android Calendar Sample](https://github.com/google/google-api-java-client-samples/blob/master/calendar-android-sample/src/main/java/com/google/api/services/samples/calendar/android/CalendarSampleActivity.java#L126) at the moment.

**Comment by AndroidDeveloperLB** [comment]
@Capstan Well, if startup speed takes time, you could make it optionally interactive, so it continues to run till you exit it (like what you have when you do "adb shell"). 
Also, only really huge Java apps that I see take a long time to run (like Eclipse and Android-Studio). Yet of course the size of the app doesn't tell anything about what it really does, so ok.

About the features, I think any thing you can do on the dashboard could be nice. For starters, the various graphs data could be a good thing to have. I like graphs :)

About the links you've provided, thank you, but I am not familiar with those topics at all. Do you mean to tell me that you can somehow connect to what the dashboard shows on Android?

**Comment by Capstan** [comment]
I think we have our wires crossed. gsutil is a command-line tool for accessing [Google Cloud Storage](https://cloud.google.com/storage/) and does not have special access to statistics or dashboards. Perhaps you're thinking of a different application?

**Comment by AndroidDeveloperLB** [comment]
It can't? But I see on the dashboard that they say it can:
https://support.google.com/googleplay/android-developer/answer/6135870#export
Which API/library/tool is the best then for those tasks?

**Comment by Capstan** [comment]
Ah, gsutil has no more knowledge of dashboards than does an ftp client or even a web browser. It relies on someone to provision data in GCS, much like the latter two require the same of an ftp server or web site.

From the link you provided, it appears the Google Play Store provisions certain reports in .csv and .zip file format. You can use the links I provided to use Java to transfer arbitrary files from GCS to your Android device. The next step, parsing them and visualizing them, is somewhat out of scope for a transfer tool.  You might be able to find some help by selecting the Contact Us link on the export page to reach out to the Google Play team.

**Comment by AndroidDeveloperLB** [comment]
The thing is that those aren't normal links. for example, the review report can be like this:

gs://pubsite_prod_rev_###/reviews

where "###" is some long number.
When you visit it without any cookies (or in private/incognito modes), it will ask for login info.
Even then, you get to a page that shows a list of files.
Parsing all of those things can be a challange, and it's a risk since Google might change the way the website is shown.

However, gsutil is supposed to do it on its own, according to the link I've written about. It should be able to download reports.
Just go to the "Export as CSV" link on most of the pages of the developer-console (or dashboard, however you wish to call it), and you will see that it has something like that:

"To access your reports programmatically download the gsutil tool. Learn more.
Direct report URIs: ..."

**Comment by Capstan** [comment]
Correct. The `gs://` pseudo-URI is a reference to a GCS object. The first path part, `pubsite_prod_rev_*###*` is the bucket name. The rest of the path `reviews` is an object name or partial path. 

gsutil simply copies all the objects under some prefix (e.g., "reviews/") which will get your file with a list of other files, but all the other files as well.

You can effect the same using the Java client library by listing the objects in the bucket (see our [simplified Java example](https://cloud.google.com/storage/docs/json_api/v1/json-api-java-samples)), using the prefix of ("reviews/") to trim results, and use the results to make calls to retrieve the individual objects.

```java
Storage.Objects.Get getObject = storage.objects().get("pubsite_prod_rev_*###*", "reviews/reviews__*YYYYMM*.csv");
ByteArrayOutputStream out = new ByteArrayOutputStream();
getObject.executeMediaAndDownloadTo(out);
```

Docs for the relevant methods:
* [storage.objects.list example](https://cloud.google.com/storage/docs/json_api/v1/objects/list#examples)
* [storage.objects.get example](https://cloud.google.com/storage/docs/json_api/v1/objects/get#examples)

Again, that will only get you the report CSV files locally, and it's up to your code to interpret them. There are commonly available CSV parsers. My understanding of Java-based visualization though is pretty limited, sorry.

**Comment by AndroidDeveloperLB** [comment]
What do you mean by "Java-based visualization" ? 
Also, how should the login phase be handled, as you can't really reach the website without doing a login first ... ?
Should I show a web browser to the user, let him login, and then use the cookies somehow?

I'm pretty sure I've seen an app that does this, but I don't remember what was its name. I've uninstalled it since it failed to login (or something similar). It asked which Google-related permissions I agree to give  to it .

**Comment by Capstan** [comment]
What website are you talking about? Are you talking about the [GCS Console](https://console.developers.google.com/storage/browser/pubsite_prod_rev_####) or something else?

The Java client uses a HTTP API rather than website scraping. For Android, you would create a credential using `GoogleAccountCredential.usingOAuth2` which will use one of the user's stored Google accounts on the device. Look up at the Android Calendar Sample link above to see how you'd build a service with that credential. Under the covers, Java will emit HTTPS requests with an `Authorization` header with an OAuth access token associated with the user, and then have permissions to anything in GCS that the user has access to.

**Comment by AndroidDeveloperLB** [comment]
The developer console website:
https://play.google.com/apps/publish/

About the credentials, wouldn't it need to ask the user to grant them? I assume it won't just give it to any app that calls those functions...
About the Calendar sample, I'm not familiar with it so I don't know which parts of it to look for this functionality. 
About Java, suppose I do get the credentials, how would I get all of the list of all of those special links?

**Comment by Capstan** [comment]
As for visualization, you were talking about dashboards and graphs. Since you're wanting to use Java on Android, I presumed you wanted to use Java to turn raw data in CSV format into some kind of graph. Thus Java-based [visualization](http://en.wiktionary.org/wiki/visualization).

**Comment by AndroidDeveloperLB** [comment]
About UI, the hard part is getting the data. After that, there are plenty of libraries out there to show it nicely.

**Comment by Capstan** [comment]
You don't need to scrape the developer console website. I don't have access to the website to see the format of the special links. You only need the bucket id to use the GCS client API. Is the problem that you don't know how to programatically ask for the bucket id for a given user?

You would need to have your application assert permissions to a particular scope. In this case, it'd be `com.google.api.services.storage.StorageScopes.DEVSTORAGE_READ_ONLY`. Then when the user went to use your application (or perhaps install it, I'm not sure when the question is posed), the user would have to explicitly permit it to access read only data on Google Cloud Storage.

The Android Calendar sample is just to establish how to create the Java GCS storage class with the right user credentials so that the calls to list objects and get objects will succeed. It's on our list of things to do to add a simple Android example so you don't have to mix and match from various samples.

**Comment by AndroidDeveloperLB** [comment]
So how do I get this list of links? I can't see anywhere on the website how to do it. If you wish, I can PM you (is it possible here?) a video of what I see.
What is the "bucket id" ? Is it this "pubsite_prod_rev_###" for the reviews, for example? If so, then yes, I can't find a way to gather those links programmatically. Only by really visiting the website.
I think that there is a unique set of links for each app.

About the permission, there are various types of permissions. Most are just given upon installation automatically, without any confirmation (other than the installation dialog). But I think this one is special.

Suppose I try out the Calendar sample, would I see this kind of usage there (permissions, credentials, using the GCS... ) ?

**Comment by Capstan** [comment]
Yes, you can [PM me](mailto:Capstan@users.noreply.github.com).

The bucket name is "pubsite_prod_rev_###". My question was not can you get the links to these (as you don't need them), but whether you can know what "###" are. i.e., can you start with that, or is this something you'd have to ask the Google Play Service for.

A GCS bucket is like a directory. You don't need to know all the links because you can list the contents of a bucket and know everything that's in it with the analog of `ls -R`. Google Play Services is creating and populating these buckets.

**Comment by AndroidDeveloperLB** [comment]
Is this an email address? If so, I've sent you what I see, in video. Please delete it when you've understood what is going on.

About the buckets, I do know the number. I just thoght it's private and shouldn't be published. 
if the list of buckets is available, how do I get it given just the package name of the app (package name is the id of the app) , for example of my tiny app : https://play.google.com/store/apps/details?id=com.lb.app_manager ?

**Comment by AndroidDeveloperLB** [comment]
I got an email that "Delivery to the following recipient failed permanently:" . I don't think it's an email address. how do you PM here?

**Comment by Capstan** [comment]
Doh! Mea culpa. Try gs-team AT google.com. I'll keep an eye out.

**Comment by AndroidDeveloperLB** [comment]
sent.
