### ISSUE TITLE
ACL false file:// URL error

### ISSUE THREAD

**Issue by theqwertman** [GoogleCloudPlatform/gsutil#272]
Running the following command
```
gsutil acl ch -u -r AllUsers:R gs://mybucketname/
```

Gives me the following error
```
CommandException: "acl" command does not support "file://" URLs. Did you mean to use a gs:// URL?
```

Running version 4.12 on Windows 8.1

**Comment by thobrla** [comment]
The command you entered is invalid, as -u requires the next argument to be the user you are changing access for.  Since "-r" immediately follows "-u", "-r" is interpreted as the target user, and AllUsers:R is interpreted as a URL to change access for.

Improving the error message is likely not easily solved unless gsutil moves to a more up-to-date argument parser.

**Comment by theqwertman** [comment]
Thanks! That solves it. Good to have this Q/A up here, now.
