### ISSUE TITLE
make gsutil work on Python 3.x

### ISSUE THREAD

**Issue by jterrace** [GoogleCloudPlatform/gsutil#29]
_Original author: mfschwa...@google.com (August 19, 2010 22:33:59)_

Currently if you try to run gsutil on Python v3.x it will get syntax errors at print statements, because Python 3.x made print into a function, so the old syntax:
  print 'abcd'
doesn't work, and instead you need:
  print('abcd')

There are likely other problems beyond just this to make gsutil work on v3.x. Moreover, at present the boto library only works on Python v2.x.

At some point, when boto moves to support Python 3.x, gsutil should as well.

_Original issue: http://code.google.com/p/gsutil/issues/detail?id=29_

**Comment by stefanv** [comment]
Please consider removing the "Priority-Low" tag.  Python 3 is fast becoming the default on many platforms.

**Comment by l3d00m** [comment]
It's been a while since the last comment here (and over 4 years since this issue was created). Is there any status update for this issue available?

**Comment by houglum** [comment]
This is still fairly low priority at this point, unfortunately.  There are a several blockers for us starting on this this work, a few of them being:

- Higher-priority tasks taking up development time
- Not all dependencies are fully compatible with Python 3 (some are partially ported, or working but without full feature parity)
- Gsutil is packaged with gcloud, which only supports Python 2 syntax currently -- users that use gsutil via gcloud would see no benefit from any Python 3 compatibility changes

**Comment by ADiegoCAlonso** [comment]
IMHO, this issue is quite high priority for a lot of developers and new comers to the GCP. So, if I take a look at my crystal ball, I see two futures:

-   **Option A**: GCP develops soon an independent version of *gsutil* that is compatible with Py3. This version will be used as reference for *gcloud* migration to Py3. Happy developers will use this new *gsutil* since the beginning.
-   **Option B**:  GCP will release the *gsutil* that is compatible with Py3 after X years together with *gcloud*. In this time, new libraries will appear that are not official but will more popular that *gsutil*. Developers will not be eager to change their codebase to use the new official library. Unofficial libraries will not be totally compatible with the API. Bottom line: it will be a mess.

**Comment by kotoroshinoto** [comment]
it seems like the priority should be raised either this year or next year, https://python3statement.org/
https://pythonclock.org/
python 2 is being slowly abandoned

**Comment by gdahlm** [comment]
Additional data that may help with priority:

RHEL 8 will drop Python 2.7 as documented in the [deprecation notice for RHEL 7.5](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.5_release_notes/chap-red_hat_enterprise_linux-7.5_release_notes-deprecated_functionality)

The lack of gsutil support for python3 constantly increases the complexity of migration projects I have been involved with.

**Comment by hnykda** [comment]
Hey! If we wanted to help with this, is there any way how to do that? This is the only High-priority task in this repo, so I am surprised it's not getting *any* traction.

**Comment by houglum** [comment]
It is getting traction :) We just haven't really been updating this thread, apologies.

@edhodapp is currently working through getting our integration tests passing for both the JSON and XML APIs.  He's testing against a project that's billed to the Cloud Storage team; I wouldn't feel comfortable asking external users to work too deeply on this phase of the project, since we don't have an in-memory emulator for GCS... thus, running the integration tests requires sending real requests that you get billed real money for :(

We've created a separate `py-six` branch which we'll be using for the Python 3 changes, but we haven't really been keeping it in sync with Ed's branch on his fork.  We plan to sync these up within the next couple of weeks.

Also, Boto3 doesn't seem particularly relevant to this thread; Boto3 includes no support for working with GCS, AFAICT.  However, the older Boto library (which gsutil uses) supports Python 3, and part of Ed's work is porting our `gs` code tree in Boto to be Py-2-and-3-compatible.

**Comment by hnykda** [comment]
Awesome! Thanks a lot for detailed response, greatly appreciated.

**Comment by houglum** [comment]
Ed's allocated time on the Python 3 project was up before we could get everything completely finished, but I checked out Ed's `py-six` branch from his fork and merged our master branch on top of it.  I also added another commit on top of that so that tests in the current runtime (PY2) are 100% passing again. See the branch (`py-six-current`) and commit linked below.  We'll resume work on this project after the holidays are over :)

Note: Ed's gsutil fork was also running against his boto fork (the `develop` branch) that had some changed to our code tree (`boto/gs`) to work toward making it PY2/3-compatible as well.

https://github.com/GoogleCloudPlatform/gsutil/commit/0a9fb95caf0ba3bbe6fd149cb2aa1057ce93a985

**Comment by hnykda** [comment]
Thanks for letting me know. I don't want to be annoying, but any ETA for when this may be done?

**Comment by houglum** [comment]
We've got a couple folks working on this full-time for the next 2 1/2 months.  Hoping to have it done by then.

**Comment by chester89** [comment]
That's good news. I have quite a number of small Python scripts waiting to
be ported to v3 because I also need gsutil to work with the same version

On Tue, Jan 22, 2019 at 10:18 PM Matt Houglum <notifications@github.com>
wrote:

> We've got a couple folks working on this full-time for the next 2 1/2
> months. Hoping to have it done by then.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/73e1b0423ed9ac8150c71573f91b224f63668973?url=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fgsutil%2Fissues%2F29%23issuecomment-456527406&userId=1053505&signature=1063c25bf7d38351>,
> or mute the thread
> <https://mailtrack.io/trace/link/045dd0463e3ab7095a1faff19c986e0f1ba6eba3?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALnfC5C_B4lciSOYxrOw5-kzYHKsPVvks5vF2QHgaJpZM4Acxzs&userId=1053505&signature=a9cc9d95e9eb199f>
> .
>


-- 
Yours faithfully,
Gleb

**Comment by houglum** [comment]
Update concerning supported Python versions:  We'd originally planned to support 3.4+, but with the announcement of Python 3.4's upcoming end of life (see [1] and [2]), we've decided to limit support to 3.5+ instead.  In pure coincidence, this has the advantage of reducing the amount of remaining work in the migration. A lot of the remaining bugs and failing integration tests only occurred on Python 3.4, and this means we no longer have to focus on those work items.

[1] https://cloud.google.com/appengine/docs/deprecations/python34
[2] https://devguide.python.org/#status-of-python-branches

**Comment by hnykda** [comment]
Sounds very reasonable to me :+1: .

**Comment by catleeball** [comment]
Master branch should now have compatibility with Python 2.7, 3.5, 3.6, and 3.7. :slightly_smiling_face:

**Comment by chris-transloc** [comment]
Is there any news on when this will be released?

**Comment by catleeball** [comment]
Hi @chris-transloc ,

I can't make any official promises, but we are currently looking at releasing gsutil v4.39 next week.

Note that once gsutil is released, if it is installed though gcloud SDK, the SDK will still gsutil with Python 2.x. In the next gcloud SDK release, the default interpreter for gsutil will be 3.x. In the gap between the gsutil release and the gcloud SDK release, you can manually tell the SDK to use a 3.x interpreter by pointing `CLOUDSDK_PYTHON` environment variable at your local Python 3.x.

I keep this issue updated when we release gsutil, and also when the newest SDK is released that will allow gcloud installations of gsutil to run under 3.x by default.

All the best,
Lee

**Comment by catleeball** [comment]
Hi everyone,

During pre-release testing, we found a couple Python 3 compatibility bugs that we need to address. This means the release won't be this week as mentioned in my last comment, but we are working hard to make a stable and production-ready release of gsutil as soon as possible. I'll be sure to keep you all updated as we progress.

All the best,
Lee

**Comment by catleeball** [comment]
Hi all,

Just a heads up that we're releasing v4.39, it won't have official Python 3 support yet since we're still ironing out some of the credential and proxy issues found doing pre-release tests. I'm working hard to make sure we have full Python 3 compatibility for 4.40, which I'm hoping will be ready in the very near future!

All the best,
Lee

**Comment by houglum** [comment]
Just released 4.40 an hour or so ago (to PyPI and as a tarball/zip -- the gcloud install still has a few safeguards prohibiting Python 3 invocation of gsutil).  This should run on Python 3.5 and up, in addition to 2.7.  We can close this nearly-decade-old bug.

Despite (what I consider to be) fairly exhaustive integration testing, there will inevitably be bugs.  Please don't comment here and try to necro this issue; open a new one instead :)

**Comment by edhodapp** [comment]
Hi Matt,

Did you end up using any of my changes, or did I screw it up too much?

-Ed

**Comment by houglum** [comment]
Haha :) We ended up grabbing most of your changes and continuing to iterate on them.  I can't give you a big enough thanks for all the progress you made.  Really glad I got to work with you, @walkerjoe, and @catleeball (and all the others who've submitted contributions to help toward Py3 compat!)

**Comment by rednap** [comment]
updated to gsutil version: 4.40, and still can't use gsutil with python3. what am I missing?

```
$ echo $CLOUDSDK_PYTHON
python

$ python -V
Python 3.7.3

$ gsutil version
ERROR: Python 3 and later is not compatible with the Google Cloud SDK. Please use Python version 2.7.x.
```

**Comment by houglum** [comment]
@rednap We still need to get some changes in to the Cloud SDK code to allow gsutil to run under Python 3.  They previously had some safeguards in to prevent users from accidentally trying to invoke it with Python 3 (back when it wouldn't have worked).  I submitted a change today that should allow users to specify the Python interpreter used to run gsutil, but we'll need a couple more weeks to test edge cases (i.e. not allowing Python 3.0 - 3.4) and make sure it's working across all the supported OSs before publishing the recommended way to switch to Py3 when invoking gsutil through gcloud's wrapper script.

If you'd like to try out Python 3 support in gsutil, you can install the standalone version.  Or, you can bypass the gcloud wrapper script for the gcloud installation (disclaimer: this can get a bit confusing - I've seen folks do this and wonder why their gcloud settings/credentials weren't being loaded, since it's the wrapper script that does all that) by running the underlying executable at `<gcloud-sdk-root>/platform/gsutil/gsutil`, rather than via the usual wrapper script at `<gcloud-sdk-root>/bin/gsutil`.

**Comment by rupestre-campos** [comment]
I had another issue, after running setup.py for gsutil it still did not work, so at least for python37 I had to change file: "\gsutil\gslib\tests\util.py" to remove errors related to lib mock_storage_service. 
As it looked like some kind of test, I commented the import to this module and also the 2 classes that use it in the script, classes are: GSMockConnection(...) and GSMockBucketStorageUri(...)
looks like it worked properly.

**Comment by thomasmaclean** [comment]
Would you be willing to submit a pull request with those changes?

**Comment by rupestre-campos** [comment]
all right, did it right now

**Comment by rupestre-campos** [comment]
just to point, I've tested only for downloading data from public google cloud buckets.

**Comment by cristifalcas** [comment]
Isn't this resolved at this moment?

**Comment by houglum** [comment]
This is indeed resolved.  Per my request in https://github.com/GoogleCloudPlatform/gsutil/issues/29#issuecomment-507410800, I'm going to close this issue again and lock it.

@thomasmaclean For any additional bugs mentioned here, e.g. https://github.com/GoogleCloudPlatform/gsutil/issues/29#issuecomment-542284508, feel free to open new issues and track them separately.
