### ISSUE TITLE
rsync ignores top-level directory on Windows

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/gsutil#295]
This might be a manifestation of https://github.com/boto/boto/pull/2823.

```
> ls E:/
    Directory: E:\
Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----          9/2/2015  11:10 AM            folder1

> gsutil rsync E:/ gs://bucket_name/
Would copy file://E:folder1\R31W7A1.txt to gs://bucket_name/R31W7A1.txt
```

Should upload to `gs://bucket_name/folder1/R31W7A1.txt`, right?

**Comment by houglum** [comment]
I can still reproduce this -- there are actually two bugs here. The first, https://github.com/GoogleCloudPlatform/gsutil/issues/523, has been fixed.  The second, which I'll use this bug to track since it's the earliest report I can find of it, is that when rsyncing using a volume as an argument (e.g. "E:\"), we're stripping off the leading path component delimiter (on Windows, this is the backslash character), then trying to combine the drive letter and the rest of the file name with no backslash inbetween.

That is, `file://E:folder1\R31W7A1.txt` should be `file://E:\folder1\R31W7A1.txt`.
