### ISSUE TITLE
Error when trying to sync file with special characters

### ISSUE THREAD

**Issue by mjwalsh** [GoogleCloudPlatform/gsutil#304]
When rsync is building the synchronization state it throws an error when trying to process this file:  morales_suenÌƒos.jpg

Building synchronization state...
At source listing 10000...
Caught non-retryable exception while listing file://D:\Apps\P_IndigoArts\gallery
_art: [Error 2] The system cannot find the file specified: u'D:\\Apps\\P_IndigoA
rts\\gallery_art\\morales_suen\u0303os.jpg'
CommandException: Caught non-retryable exception - aborting rsync

**Comment by mfschwartz** [comment]
Hi - I've been able to repro this problem, and found it only happens on Windows, and only when using gsutil rsync -r. (Using gsutil rsync with a directory containing unicode chars works fine.) Unfortunately I haven't had much time to dig in further yet.

**Comment by mfschwartz** [comment]
I have a partial fix for this problem - I say "partial" because it makes gsutil work with the Unicode filename you gave as an example but I know of another case that doesn't work. Unfortunately it's difficult to make Unicode work 100% correctly on Python 2.x on Windows because Windows uses its own custom encoding (cp1252).

Anyway, this fix will be included in gsutil release 4.16.
