### ISSUE TITLE
gsutil cp in shell script

### ISSUE THREAD

**Issue by grianna** [GoogleCloudPlatform/gsutil#313]
i have an issue with shell scripting for a cron job we require, using Centos 6
The following command:
"gsutil cp -r /home/dbkup/2015-11-12 gs://myweb/testfiles" 
runs happily from the terminal screen and as an at job. No issues.
However when I place it in a shell script, e.g. cloudbkup.sh, it invariably fails.
If i replace the gsutil cp command in the same shell script with an ls command e.g. gsutil ls gs://myweb that works fine, just seems to be the cp command. 
This is just one of the errors returned, others refer to unfound URL, none of which makes sense as the script runs ok outside the shell script!
Copying file:///home/dbkup/2015-11-12/system/files/_etc_named.conf.gz
[Content-Type=text/x-config]...
/system/files/_etc_named.conf.gz: 2.94 KiB/2.94 KiB
BadRequestException: 400 Invalid Value

**Comment by thobrla** [comment]
Thanks for the report

Can you mail the stdout and stderr of the successful (terminal) and failing (script) cases with the -D flag, i.e.,
`gsutil -D cp -r /home/dbkup/2015-11-12 gs://myweb/testfiles`
to gs-team@google.com?

**Comment by grianna** [comment]
Hi,
not sure but are these the files you requested? They were output on the screen during the respective operations.

Rgds

John

[FailureFrombashscript.txt](https://github.com/GoogleCloudPlatform/gsutil/files/33265/FailureFrombashscript.txt)
[Success_from_commandline.txt](https://github.com/GoogleCloudPlatform/gsutil/files/33266/Success_from_commandline.txt)

**Comment by thobrla** [comment]
I deleted your reply from GitHub because it contained access tokens for your data, which is why I requested you send the output to gs-team@google.com.  So instead of posting the output here, can you please mail them to gs-team@google.com?  Also, for the success case, can you please send the stderr in addition to the stdout of the command?  You can capture it like so:

`gsutil -D cp -r /home/dbkup/2015-11-12 gs://myweb/testfiles 2> success-stderr > success-stdout`

Then you can send success-stderr and success-stdout to gs-team@google.com.

In the failure case, it looks like one of the files in /home/dbkup/2015-11-12 contains a carriage ('\r' character) which is not allowed according to the [Google Cloud Storage Object Name Requirements](https://cloud.google.com/storage/docs/bucket-naming?hl=en#objectnames).

**Comment by grianna** [comment]
I will do that, regarding that failure due to the \r character - why should it fail only when run in a bash script, and succeed when run directly at the command prompt? It is the exact same command, same files, same destination and source, so how can that be explained? Will mail the files shortly.

**Comment by thobrla** [comment]
According to our discussion, it looks like your script indeed includes carriage return characters in addition to newlines.  When you're using the command problem I don't think the carriage return character is passed, thus the difference.
