### ISSUE TITLE
rsync does not detect when local file changes content without changing size

### ISSUE THREAD

**Issue by jxson** [GoogleCloudPlatform/gsutil#343]
Hey all,

I work on a decent size team and we use the gsutil across a wide number of projects to support our devops and deploy tasks. If the `-m` flag is left off there will be a warning when using commands like `gsutil rsync`, this leads a reasonable developer to do the right thing and update any scripts which shell out to `gsutil` to use the `-m` flag.

A problem with this scenario, that has bitten us numerous times, is that the content matching causes edits like single line config changes to be treated as if there is no change at all. The `gsutil` tool will treat locally updated files as if they are the same as outdated content in the storage buckets. Sometimes we can catch this early but often it takes quite a bit of debugging and head scratching to arrive at the cause of unexpected behavior being the `-m` flag.

Sometimes in our code the flag will be removed, only to be added again later by a different, well meaning developer later.

I don't have a specific solution to this but have been bitten by numerous times. I think, at the very least the warning/suggestion to use the flag should clearly mention this undesired side effect and what other flags should be added to get around issues if it is used.

**Comment by thobrla** [comment]
This behavior doesn't have anything to do with the presence of the -m option.  Instead, it is related to the -c option - see the "CHANGE DETECTION ALGORITHM" section of `gsutil help rsync`.

By default, gsutil does not perform a full checksum of local files, but checks only their sizes.  If you expect that files will change contents without changing size, you'll need to use the -c option to trigger checksumming that will detect these changes.  The downside is that this generates a lot of local disk I/O, since every local file within the scope of the rsync must be read.  This is why the option is turned off by default.

**Comment by thobrla** [comment]
Feel free to re-open if this doesn't adequately address your issue.

**Comment by jxson** [comment]
Hi @thobrla.

I just tried to reproduce and I think I misattributed the behavior to the `-m` change do to white space changes between local edits and git updates. Sorry about the misdirection there.

I think the real problem is that the default change algorithm is not sensitive enough to detect single line changes for things like ip addresses, hostnames, etc. And usually we don't figure it out until a mistake has been made.

**Comment by thobrla** [comment]
Right - like I mentioned above, you can use the -c flag to take care of this, but it will substantially increase the local disk I/O and make the command run more slowly.  Because of the performance impact, it's unlikely that we'll change that default.

**Comment by thobrla** [comment]
FYI, starting with gsutil 4.20, `gsutil rsync` now uses a change detection algorithm based on the file''s modification time (falling back to checksums if that is not available), which should detect single line changes without a large performance penalty after it's run once.

**Comment by Somebi** [comment]
When copy project files, for example javascript files, this is very important to check checksum, because size won't do the job. Simple example, just swap arguments in the function, this won't change the size of file, but will change the logic of function and this won't be copied with rsync, without -c flag. I have spent some time to understand this one...
