### ISSUE TITLE
Request: permit both source and destination for input lists

### ISSUE THREAD

**Issue by tantrev** [GoogleCloudPlatform/gsutil#349]
Would be nice if the -I command permitted both the source and destination to be specified.  Currently it only seems to support one list of either source or destination.

**Comment by thobrla** [comment]
Can you explain your use case in more detail?  Since there will only ever be one destination, the value of streaming the destination argument seems minimal.

**Comment by tantrev** [comment]
Sure thing.  So the use case is just batch downloads/uploads that have different directories from each other within the upload or download.  For example, right now I do separate gsutil calls:

gsutil -m cp gs://testBucket/testDirectory1/testFile1.txt /localDirectory/testDirectory3/testFile1.txt
gsutil -m cp gs://testBucket/testDirectory2/testFile1.txt /localDirectory/testDirectory4/testFile2.txt

It'd just be nice to be able to specify the two parameters after "cp" in a list.  I'm not sure how gsutil currently handles its input list, I just figured it is probably more efficient than my current method of spawning thousands of individual gsutil instances. :P

**Comment by thobrla** [comment]
This sounds like a request to specify multiple destinations in a single command, and map one source to one destination.  Is that correct?

If so, we're unlikely to implement that because it diverges from the behavior of Unix-style `cp` and there is a lot of potential for confusion around whether an argument represents a source or destination.

Is there are a reason that the local directory names need to differ from those that are in the cloud?  Can you give more detail about what you are actually trying to accomplish by moving these files?

**Comment by tantrev** [comment]
My apologies, I had a typo above.  I meant to write:

gsutil -m cp gs://testBucket/testDirectory1/testFile1.txt /localDirectory/testDirectory3/testFile1.txt
gsutil -m cp gs://testBucket/testDirectory2/testFile2.txt /localDirectory/testDirectory4/testFile2.txt

It's really just mapping one source to one destination, individually, in batch.  In any event, it's no matter - I'll just continue using my spawning methods.  You are absolutely correct in that it deviates from  traditional `cp` behavior.

**Comment by thobrla** [comment]
Thanks.  I'm going to close this issue, then.
