### ISSUE TITLE
Error running from crontab

### ISSUE THREAD

**Issue by wacamoe** [GoogleCloudPlatform/gsutil#350]
i have a weird issue when running a script using gsutil from a crontab job. When I run a 'cp' from a crontab job, I am left with a bunch of '.gztmp' files instead of true raw files. However, when I run the command normally, I get the source files. I thought this was due to an update, but it also occurs on 4.15.

Any ideas?

**Comment by pstemari** [comment]
Have you checked your environment settings for the script? Cronjobs are
notorious for running with empty PATH and/or LD_LIBRARY_PATH settings.

—Paul
On Apr 4, 2016 10:30 PM, "Kyle Grymonprez" <notifications@github.com> wrote:

i have a weird issue when running a script using gsutil from a crontab job.
When I run a 'cp' from a crontab job, I am left with a bunch of '.gztmp'
files instead of true raw files. However, when I run the command normally,
I get the source files. I thought this was due to an update, but it also
occurs on 4.15.

Any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/gsutil/issues/350>

**Comment by wacamoe** [comment]
I've handled PATH, but haven't checked LD_LIBRARY_PATH. Funny thing is that
it worked up until the end of March and then only started failing recently.
On Apr 5, 2016 8:32 AM, "Paul J. Ste. Marie" <notifications@github.com>
wrote:

Have you checked your environment settings for the script? Cronjobs are
notorious for running with empty PATH and/or LD_LIBRARY_PATH settings.

—Paul
On Apr 4, 2016 10:30 PM, "Kyle Grymonprez" <notifications@github.com> wrote:

i have a weird issue when running a script using gsutil from a crontab job.
When I run a 'cp' from a crontab job, I am left with a bunch of '.gztmp'
files instead of true raw files. However, when I run the command normally,
I get the source files. I thought this was due to an update, but it also
occurs on 4.15.

Any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/gsutil/issues/350>

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/gsutil/issues/350#issuecomment-205859744>

**Comment by thobrla** [comment]
Can you run `gsutil -D cp ...` in your crontab job and collect the debug logs (stderr)?  The temporary gzip files are created in the same location as their eventual unzipped counterparts, so there shouldn't be any issues with opening the final (uncompressed) file for writing.  That leads me to guess that something is going wrong in between when the gzipped file finishes downloading and the decompression code runs.

For files > 10MB in size, you should see in the debug logs "Uncompressing temporarily gzipped file to ..."

**Comment by wacamoe** [comment]
@thobrla checking now. In my debugging, i simplified the pull from two accounts down to one and it ran correctly with the -D (and -m) flags. I added the second account back in, both with -D to see if I see any additional errors.

Thanks!

**Comment by wacamoe** [comment]
Weird.....i didn't do anything different, but the job is now completing successfully.....
