### ISSUE TITLE
gsutil cp with wildcard in source path produces nonsensical destination paths

### ISSUE THREAD

**Issue by Quuxplusone** [GoogleCloudPlatform/gsutil#397]
cd /tmp
    echo 'hello world' > /tmp/hello
    gsutil cp /tmp/hello 'gs://mybucket/example/1234567/moretext/1234567/hello'
    gsutil cp /tmp/hello 'gs://mybucket/example/1234/moretext/1234/hello'
    rm -rf /tmp/dummy ; mkdir -p /tmp/dummy
    gsutil cp -r 'gs://mybucket/example/*/moretext' /tmp/dummy
    find /tmp/dummy/ -type f

The output is:

    /tmp/dummy/234/moretext/1234/hello
    /tmp/dummy/234567/moretext/1234567/hello

Notice that the first character of each wildcarded path is mysteriously missing. (It disappeared during the download, not during the upload; the files in GCS have the correct names.)

I'm actually a bit surprised by my test case above. In the wild, before I anonymized and shortened the paths, what I observed was that one file would come through unscathed and then all the other files would have truncated or duplicated names. It seems to be due to logic somewhere deep inside `gsutil cp` that does "Compute the destination path by dropping a certain number of characters from the front of the source path"; but that logic fails to account for the fact that the same "source path" can correspond to different numbers of characters, if it contains a wildcard. I.e., what I *expected* to see in my test case above was either

    /tmp/dummy/1234/hello
    /tmp/dummy/ext/1234567/hello

or

    /tmp/dummy/1234567/hello
    /tmp/dummy/4/hello

**Comment by thobrla** [comment]
Thanks for the report.  This is indeed a bug in gsutil.

The culprit is this line in ConstructDstUrl: https://github.com/GoogleCloudPlatform/gsutil/blob/8e43b69fef591777441fb38e29ab92c91fb6d109/gslib/copy_helper.py#L638

We're trying to construct the destination path by removing the final subdirectory of the source before naming the destination.  However, in this case the "final directory" is a wildcard which expanded to the full destination path.  In more detail, before we execute that line, the system's state is something like:

    source_path_sans_final_dir = 'gs://source-test-bucket/*'
    exp_src_url.versionless_url_string = 'gs://source-test-bucket/Test/sub-test/foo.txt'

Here, `source_path_sans_final_dir` is problematic here because it doesn't represent a real path.

**Comment by Quuxplusone** [comment]
Thanks for the quick diagnosis; looking forward to the fix. :)
Our initial attempt involved a source path with even more wildcards, e.g.

    gsutil cp -r 'gs://mybucket/example/*/moretext/*/*.txt' /tmp/dummy

so we'd love to see a fix that either made such paths work unbuggily, or else produced a friendly error message indicating that such paths were unsupported.  (I mention this because I suspect that making multiple wildcards work unbuggily might be even harder than making single wildcards work.)

**Comment by thobrla** [comment]
Thanks for the detail.

I have a fix under review internally.  Barring review issues, this fix should fully resolve these wildcards - the goal will be to have it behave with the exact same semantics as running Unix-style `cp` locally.
