### ISSUE TITLE
No such file or directory CommandException: 1 file/object could not be transferred

### ISSUE THREAD

**Issue by ahmednaguib** [GoogleCloudPlatform/gsutil#403]
I am using gsutil to upload a folder which has some symlinks, the problem is that some of these files are false symlinks ( Unfortunately, that's the case)

Here is an example of the command I am using:

    gsutil -m cp -c -n -e -L output-upload.log -r output gs://my-storage

and I get the following:

    [Errno 2] No such file or directory: 'output/1231/file.mp4'
    CommandException: 1 file/object could not be transferred.

Is there a way to make gsutil skip this file or fail safely without stopping the upload ?

**Comment by thobrla** [comment]
I think this may be a bug in gsutil cp - the -e option currently only excludes symlinks in top-level arguments, but it should apply to arguments iterated recursively as well.

I think rsync -e should work properly in the meantime; does that work for your scenario until the bug is fixed?

**Comment by thobrla** [comment]
Fix will be released with gsutil 4.23

**Comment by yaseenkhanmohmand** [comment]
Okay,

So I had the exact same error

`yaseen@forbigclicks:~$ ls
‘conversion_records_2018_7_to_8.csv’  export.csv`

and I could not open conversion_records with a simple 
`head -1 conversion_records_2018_7_to_8.csv`
OR
`head -1 'conversion_records_2018_7_to_8.csv'`
but was able to open export.csv conversion records kept throwing an error showing no such file or directory.

The fix for me was to copy the exact comma format in the ls output and use that , it had a different kind of commas around the name for some reason. (I am thinking because of the digits in the name.

so i did 

 `head -1 ‘conversion_records_2018_7_to_8.csv’`

And it worked!
