### ISSUE TITLE
md5 is not calculated when downloading a big file

### ISSUE THREAD

**Issue by ggittu** [GoogleCloudPlatform/gsutil#411]
Downloading a big file the md5 is not calculated (field is empty) in the manifest file. We are using more threads and process to achieve parallel download. So its really important for us to check the integrity of the file downloaded?

**Comment by houglum** [comment]
The MD5 listed here is populated from the object metadata, rather than calculated locally upon download.  Objects that are composed of more than 1 object (e.g. something created via `gsutil compose`, or uploaded via a parallel composite upload) do not have an MD5 in their metadata.  They do, however, have a crc32c hash.  You can see if the object(s) in question falls under this category by calling `gsutil ls -L gs://path/to/your/object` - the ls output for such objects will display a "Component-Count:" row with the number of components making up the object.

If you need to check the integrity of such files after download, you should be able to parse through the manifest file, identify those that you need to verify, and compute their crc32c hash, comparing it with the object's hash from `gsutil ls -L`.
