### ISSUE TITLE
Strange behavior with gsutil cp, gsutil  rsync and folders symlink

### ISSUE THREAD

**Issue by ilyaskorik** [GoogleCloudPlatform/gsutil#412]
Hello! 

Faced strange behavior with gsutil and symlinks.

1) I created a symlink for a folder, like 'ln -s folder1 folder2', where folder1 is regular folder

2) Then I tried to copy this symlink into the cloud:
- 'gsutil rsync -r ./ gs://bucket/', but gsutil does not see symlink and transfer only folder1 
- 'gsutil cp folder2 gs://bucket/' but gsutil tries to copy symlink as a regular folder and throw 'Omitting directory "file://./folder2". (Did you mean to do cp -r?)'

What am I doing wrong?

Google Cloud SDK [146.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/usr/lib/google-cloud-sdk]
Installed Components:
  core: [2017.02.28]
  core-nix: [2017.02.28]
  gcloud-deps: [2017.02.28]
  gcloud: []
  beta: [2017.02.28]
  gsutil-nix: [4.22]
  gcloud-deps-linux-x86_64: [2017.02.28]
  gsutil: [4.22]
  bq: [2.0.24]
  alpha: [2017.02.28]
  bq-nix: [2.0.24]
System PATH: [/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games]
Cloud SDK on PATH: [False]
Kubectl on PATH: [False]

Installation Properties: [/usr/lib/google-cloud-sdk/properties]
User Config Directory: [/root/.config/gcloud]
Active Configuration Name: [default]
Active Configuration Path: [/root/.config/gcloud/configurations/config_default]

**Comment by houglum** [comment]
You're not doing anything wrong; we don't support following symlinks for directories.  When recursively copying, we use os.walk() to recurse into directories - it doesn't follow symlinks by default because it has no protection against infinite loops.  We've discussed this specific issue quite a few times and come up with several reasons for not recursing into symlinks for directories... the main reason being that there's no support for symlinks in GCS buckets, thus we're unable to provide a symmetric representation of the local file system and cloud destination after an rsync operation.  If we did have such support, then a local-to-cloud rsync operation that followed symlinks would result in an accurate, symmetrical mapping between the local file system and the uploaded objects.  But, since that's not the case, we have the scenario where performing a local-to-cloud rsync followed by a cloud-to-local rsync may not be a symmetric operation.  This asymmetric synchronization results in unexpected behavior for the backup-followed-by-restore scenario, so we'd rather avoid it.

**Comment by ilyaskorik** [comment]
I use GCS for deploy a project. And it is a very common scenario, when the project has symlinks.

Popular FTP clients solve this problem when transferring files from Linux to Winfows, converting symlinks to regular files. I would be more than satisfied with this option.

Also, this issue should be well covered in the documentation. I did not find in it anything about the fact that the GCS does not support symlinks.

Thanks!

**Comment by houglum** [comment]
You're absolutely correct that we could document this better - I've made myself a note to take care of this soon.

Also, while we don't officially support following symlinks for directories, one fairly easy workaround is to use your own local, separate copy of gsutil and make a one-line change: in `gslib/wildcard_iterator.py`, the `_IterDir()` method contains a call to `os.walk()`  -- adding the `followlinks=True` argument to `os.walk()` will produce the behavior you want, but be warned that it has no protection against infinite loops.

**Comment by houglum** [comment]
Documented this in the rsync help in https://github.com/GoogleCloudPlatform/gsutil/commit/866b7164a0b50d0440de6de3a645ee1b69dd7079
