### ISSUE TITLE
Use batch operation (delete)

### ISSUE THREAD

**Issue by xmedeko** [GoogleCloudPlatform/gsutil#420]
When I need to delete many objects `gsutil rm -r gs://.../` I see the `gsutil` issues a separate HTTP DELETE requests for each object. May this be sped up by using batch requests (https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch)?

I would need to speed up especially deleting objects and moving between buckets. We have millions of objects and that take time (hours) even with the `-m` switch.

**Comment by houglum** [comment]
<div>We'd considered adding support for this in gsutil at one point, but decided not to prioritize implementing it for a few reasons:
<br>
<br>* The -m option already makes use of multiple threads (and processes, assuming you're not on Windows and limited to 1) to speed up operations on large collections. Increasing the value of the parallel_thread_count and parallel_process_count boto options even further can yield significant speedups for commands like rm where you're not transferring data and just issuing one call per object.
<br>* Because of the way batch operations are implemented in the service, we found that the speedup wasn't terribly significant in most cases
<br>* It added complexity for marginal benefit
<br>* Finally, we found that in several cases where users were requesting this functionality, it was to delete all the objects in their bucket -- for large collections of objects, doing this via object lifecycle and the Delete action [1] is generally much faster than trying to do it yourself
</div>
<br>

\[1\] https://cloud.google.com/storage/docs/lifecycle

**Comment by xmedeko** [comment]
Thanks for the answer, interesting informations. I know the lifecycle, but it's not suitable for this particular case, we need rarely to delete many objects manually. Also we need to copy them between buckets to archive them more often. But I am not sure if the copy operation may be batched. (Maybe we can use object versioning instead, I'm going to study it).

I see you have done some benchmarks already. I use `-m` switch already, but do not know how to fine tune the `parallel_thread_count` and `parallel_process_count`. I use GCE n1-highcpu-4 Linux machine - are the default `.boto` values optimal?

**Comment by houglum** [comment]
It honestly varies from machine to machine (what else you're running on the machine, how many processors it has, etc.).  I did a quick test on an n1-standard-4:
- Created 2000 one-byte files named shortfile1, shortfile2, etc.
- Uploaded them to bucket1: `gsutil -m cp ./shortfile* gs://bucket1`
- Transferred them between buckets: `time gsutil -m cp gs://bucket1/shortfile* gs://bucket2/`
  - This took ~26s with the defaults (process count of 4, thread count of 5)
- Did the same thing, but to a different bucket and using 16 for process and thread count: `time gsutil -o 'GSUtil:parallel_thread_count=16' -o 'GSUtil:parallel_process_count:16' -m cp gs://bucket1/shortfile* gs://bucket3`
  - This took ~13s

Generally, increasing thread count doesn't help quite as much as increasing process count because of Python's global interpreter lock, but still shows a non-negligible improvement... and once you get past a certain number of processes and threads, you start evening out or even losing performance since your workers are competing for system resources - we actually limit the process count to 32 to help avoid this, IIRC.  So, on an n1-standard-4 doing cloud-to-cloud copies, I'd probably go with 16+ processes and a reasonable amount of threads... based on my admittedly lazy "benchmarks" below :)

8 processes, 4 threads --> 26s
8 processes, 8 threads --> 25s
8 processes, 16 threads --> 18s

16 processes, 4 threads --> 16s
16 processes, 8 threads --> 15s
16 processes, 16 threads --> 13s

32 processes, 4 threads --> 33s  # Yuck.
32 processes, 8 threads -->  17s
32 processes, 16 threads -->  13s

**Comment by xmedeko** [comment]
Thanks for the complete information. I'll to increase the processes and threads. Closing the issue.
