### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS with service account

### ISSUE THREAD

**Issue by pydevops** [GoogleCloudPlatform/gsutil#447]
It is more about the question why Google Cloud SDK is not using the google-cloud-python in general. This includes gcloud and gsutil CLI, both of them would not honor GOOGLE_APPLICATION_CREDENTIALS. This has caused confusion and inconsistency during the Dockerizing various CICD.  gcloud, gsutil and various google-cloud client libraries based tool, kubectl, Terraform are used all together.  

It would be consistent for gcloud and gsutil to use GOOGLE_APPLICATION_CREDENTIALS  to override the defaults.

**Comment by houglum** [comment]
As far as why we're not using google-cloud-python, we found that its media transfer implementations were not as performant as what we had written in gsutil (at the time we did the comparison, anyway).  @thobrla has more context around this than I do.

As for Application Default Credentials, the use case here is allowing a program a user has written to easily get credentials via the auth precedence defined in the [ADC docs](https://developers.google.com/identity/protocols/application-default-credentials).  Neither gcloud nor gsutil are end-user-authored programs, and both already have well-documented auth setup processes.  Adding support for ADCs _in order of precedence defined in the docs_ might break existing auth workflows for gsutil (suddenly using your gcloud ADC file instead of the `gs_service_key_file` you had configured, for example).  However, I'd be open to adding a check for ADCs (via checking for the `GOOGLE_APPLICATION_CREDENTIALS` env var, and looking for the gcloud ADC file if we're running as part of a packaged-with-gcloud installation) as a fallback if no other auth handlers are available.

**Comment by thobrla** [comment]
For context, google-cloud-python doesn't support the multiprocessing facilities that gsutil needs to achieve maximum throughput.  Also, gsutil's codebase is sizable, so even if the library did support it, the engineering effort needed to port would large.

**Comment by pydevops** [comment]
fair enough. Thanks for the information.

**Comment by cjmcgraw** [comment]
Years later still having this issue.

my docker-compose.yml looks like this:

```
version: 3

services:
  webservice:
      ...
      volumes:
        - $GOOGLE_APPLICATION_CREDENTIALS:/creds
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: /creds
```

Running the equivalent of the following code:

```python
import subprocess

subprocess.run(["gsutil", "ls"])
```

I then use different environmental variables conditional on environment.

locally: `GOOGLE_APPLICATION_CREDENTIALS=${HOME}/.config/gcloud/application_default_credentials.json`
ci/cd: `GOOGLE_APPLICATION_CREDENTIALS=/some-service-account.json`
production: `GOOGLE_APPLICATION_CREDENTIALs=/some-prod-service-account.json`

However switching between the service account and local development very quickly becomes cumbersome. Is there a solution using gcloud commands at docker container startup to allow me to auth `gsutil` with either my authorized_user or service_account (given that I don't know whcih it will be)

**Comment by pydevops** [comment]
https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account can do the trick for cicd and production, as long as the service account json file is taken care properly as a secret. 
For the "locally" use case, either https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login can help or you need to use a different service account for being consistent. 
GOOGLE_APPLICATION_CREDENTIAL is only meaningful for SDK, not for gcloud, gsutil. 
Hope this helps

**Comment by cjmcgraw** [comment]
@pydevops I imagine that is the following code as the entrypoint to the docker container then:

```bash
#! /usr/bin/env bash

account_type=$(cat /creds | jq '.type')
if [[ "${account_type}" = "service_account" ]]; then
    gcloud auth activate-service-account --key-file=/credsw
elif [[ "${account_type}" = "authorized_user" ]]; then
    # gcloud auth login requires the user to interact with the CLI prompt
    # which they already have from their host machine. Configuring this
    # case doesn't seem to work.
    exit 1
fi

python main.py
```

The problem I forsee is that second condition in the if statement. There doesn't seem to be anyway I can find documented about how to `auth login` if you already have the ADC available.

**Comment by cjmcgraw** [comment]
I have created a separate ticket for this. As I imagine its outside of the scope of this one now
