### ISSUE TITLE
regex match failed on zsh

### ISSUE THREAD

**Issue by mrmiywj** [GoogleCloudPlatform/gsutil#499]
Hi guys,
I found gsutil failed on zsh but worked well on bash when trying to use regex in the url.
The problem is that:
When I try to cp files in a dir from gcloud storage to an instance on gcloud, it worked well.

> $ echo $SHELL
> /bin/bash
> $ gsutil cp -r gs://xxxx/real_output/* .
> Copying gs://xxxx/real_output/_SUCCESS...
> Copying gs://xxxx/real_output/part-00000...
> Copying gs://xxxx/real_output/part-00001...
> / [3 files][314.0 KiB/314.0 KiB]
> ==> NOTE: You are performing a sequence of gsutil operations that may
> run significantly faster if you instead use gsutil -m -o ... Please
> see the -m section under "gsutil help options" for further information
> about when gsutil -m can be advantageous.
> 
> Copying gs://xxxx/real_output/part-00002...
> Copying gs://xxxx/real_output/part-00003...
> Copying gs://xxxx/real_output/part-00004...
> Copying gs://xxxx/real_output/part-00005...
> Copying gs://xxxx/real_output/part-00006...
> \ [8 files][  1.0 MiB/  1.0 MiB]
> Operation completed over 8 objects/1.0 MiB.
> 

But it failed on my mac with zsh:
> $echo $SHELL
> /bin/zsh
> $gsutil cp -r gs://xxxx/real_output/* .
> zsh: no matches found: gs://xxxx/real_output/*

**Comment by houglum** [comment]
This is an issue with how zsh, with default settings, handles the __*__ character.  Try surrounding your argument in single (or double? I haven't tried) quotes.  See https://github.com/GoogleCloudPlatform/gsutil/issues/471 for a similar issue :)

Since this is more of an issue dealing with zsh, I'm going to mark this issue as closed.
