### ISSUE TITLE
Short option for hash

### ISSUE THREAD

**Issue by gsf** [GoogleCloudPlatform/gsutil#511]
For use in scripting it would be great if `gsutil hash` had an option to output only the hash. It's currently verbose, requiring parsing of the output to get the hash string:

```
# gsutil hash -c /etc/motd
Hashes [base64] for /etc/motd: B]
        Hash (crc32c):          4+27Ig==

Operation completed over 1 objects/282.0 B.
# gsutil hash -c /etc/motd 2>&1 | grep crc32c | awk '{ printf $3 }'
4+27Ig==
```

**Comment by gsf** [comment]
Slightly nicer way to get that hash:

```
# gsutil -q hash -c /etc/motd | grep crc32c | awk '{ printf $3 }'
4+27Ig==
```

**Comment by gsf** [comment]
One more iteration:

```
# gsutil -q hash -c /etc/motd | awk '/crc32c/ {printf $3}'
4+27Ig==
```

**Comment by houglum** [comment]
Files and objects can have multiple hash types (MD5 and CRC32C), so we need some sort of label to indicate the type of each hash.  Also, we only respect the -c and -m options when we actually need to calculate the hash (i.e. for file URIs, not for object URIs, since we just read them from the retrieved metadata); some people probably rely on this behavior, so I'd prefer not to make a backward-incompatible change and break them.

I understand the appeal of not having to parse through command output, but I don't think it's worth adding more code paths and changing the output format depending on which combination of URI-type and set of options you passed in.  It would be more reasonable to add an option to print our output in some structured, easily-parsable format like JSON, but at that point you're still having to parse through the output with something like `jq` or `awk` anyway.  Given these points, I'm going to close this issue.
