### ISSUE TITLE
Virtualenv and gsutil seem to have some conflicts in gcloud compute instances

### ISSUE THREAD

**Issue by bluecoconut** [GoogleCloudPlatform/gsutil#516]
In a gcloud compute instance (debian or Ubuntu 16.04 tested):

Setup:
```
sudo apt-get update
sudo apt-get install -y python-pip
pip install --upgrade virtualenv
virtualenv test
```

Command that work when run without virtualenv.
```
gsutil ls gs://gcp-public-data-landsat
```

Command that fails:
```
source test/bin/activate
gsutil ls gs://gcp-public-data-landsat
```

Error thrown:
```
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil.py", line 113, in RunMain
    import gslib.__main__
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 39, in <module>
    import boto
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/boto/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/boto/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/boto/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/usr/lib/python3/dist-packages/google_compute_engine/boto/compute_auth.py", line 19, in <module>
    from google_compute_engine import logger
ImportError: No module named google_compute_engine
```

Special note: "gcloud compute" commands work fine from within virtualenv. only gsutil shows this problem.
(Eg. the following command works from both within and outside of the virtualenv)
```
gcloud compute ssh [instance-name]
```

**Comment by houglum** [comment]
This path import trouble you're seeing comes from the /etc/boto.cfg file that's included in our GCE images, which tells boto to load the google_compute_engine package from the directory that's not in the PYTHONPATH (because you're in a virtualenv).  The gsutil version that comes with the gcloud SDK on GCE instances is not intended to be used within virtual environments out-of-the-box... it's intended to "just work" out-of-the-box -- to achieve this, the default GCE setup relies on some assumptions based on preset paths where necessary packages can be found.

If you want to use a virtualenv on GCE, I'd recommend either:

1) Don't rely on using GCE's automagical compute engine credentials, supplied by the google_compute_engine Python package; you can do this in several ways (setting the `BOTO_CONFIG` environment variable so that Boto doesn't look for and load /etc/boto.cfg, or just delete the /etc/boto.cfg file... or comment out its plugin_directory attribute).

2) Or, if you still want to use that package, you'll need to install it in your virtualenv and override a setting in /etc/boto.cfg - the easiest way of doing this is by setting it in your $HOME/.boto file, since Boto attempts to load that file __after__ /etc/boto.cfg:

Once in your virtual env, run `pip install google_compute_engine`, then create a $HOME/.boto file that overwrites the Plugin:plugin_directory boto option, meaning that it should contain this:

```
[Plugin]
# Replace with the path to this package that's within your virtualenv
# The path to use can be found via running:
# $ python -c 'import google_compute_engine, os; print(os.path.join(google_compute_engine.__path__[0], "boto"))'
plugin_directory = /home/houglum/.virtualenvs/my-env/local/lib/python2.7/site-packages/google_compute_engine/boto
```

**Comment by haraldschioberg** [comment]
As far as this affects a clean install of google-cloud-sdk on a GCE `ubuntu-1804-lts` image. This is a pretty vanilla bionic instance on GCE , with just the `google-cloud-sdk` from `deb https://packages.cloud.google.com/apt cloud-sdk-bionic main` installed. 

`gsutil` will not work here, with the `ImportError: No module named google_compute_engine`. 

`BOTO_PATH=/foo gsutil` works. 

```
cat /etc/boto.cfg 
# This file is automatically created at boot time by the /usr/lib/python
# 3/dist-packages/google_compute_engine/boto/boto_config.py script. Do
# not edit this file directly. If you need to add items to this file,
# create or edit /etc/boto.cfg.template instead and then re-run
# google_instance_setup.

[GSUtil]
default_project_id = 639040800391
default_api_version = 2

[GoogleCompute]
service_account = default

[Plugin]
plugin_directory = /usr/lib/python3/dist-packages/google_compute_engine/boto
```

```
$ find / -wholename \*google_compute_engine/boto\* 2>/dev/null
/usr/lib/python3/dist-packages/google_compute_engine/boto
/usr/lib/python3/dist-packages/google_compute_engine/boto/compute_auth.py
/usr/lib/python3/dist-packages/google_compute_engine/boto/boto_config.py
/usr/lib/python3/dist-packages/google_compute_engine/boto/__init__.py
/usr/lib/python3/dist-packages/google_compute_engine/boto/__pycache__
/usr/lib/python3/dist-packages/google_compute_engine/boto/__pycache__/__init__.cpython-36.pyc
/usr/lib/python3/dist-packages/google_compute_engine/boto/__pycache__/compute_auth.cpython-36.pyc
/usr/lib/python3/dist-packages/google_compute_engine/boto/__pycache__/boto_config.cpython-36.pyc
```

```
apt show google-cloud-sdk
Package: google-cloud-sdk
Version: 245.0.0-0
Priority: optional
Section: misc
Maintainer: Google Cloud SDK Authors <https://code.google.com/p/google-cloud-sdk/>
Installed-Size: 159 MB
Depends: python2.7
Recommends: python-crcmod
Suggests: google-cloud-sdk-app-engine-java, google-cloud-sdk-app-engine-python, google-cloud-sdk-pubsub-emulator, google-cloud-sdk-bigtable-emulator, google-cloud-sdk-datastore-emulator, kubectl
Conflicts: gsutil
Homepage: https://cloud.google.com/sdk/
Download-Size: 21.9 MB
APT-Manual-Installed: yes
APT-Sources: https://packages.cloud.google.com/apt cloud-sdk-bionic/main amd64 Packages
Description: Utilities for the Google Cloud Platform
```
