### ISSUE TITLE
Cannot install GSutil - Cannot Uninstall six

### ISSUE THREAD

**Issue by grantkemp** [GoogleCloudPlatform/gsutil#588]
When I follow the instructions to install gsutil - I get this error: 
Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by houglum** [comment]
You've probably got an older version of `six` installed than what we require in setup.py, and it wasn't installed via `pip`.

I'd suggest one of these approaches, in order of preference:
-  Installing gsutil in its own virtualenv.
-  Installing gsutil to the user install directory (`pip install gsutil --user`, or `pip install gsutil --ignore-installed six --user` as mentioned in [this StackOverflow post](https://stackoverflow.com/questions/50954182/python-cannot-uninstall-six-while-pip-install-tld)).
-  Updating your `six` package separately before installing gsutil (this is least preferred because it may break packages installed in the _system_ package directory that could only work with an older version).
