### ISSUE TITLE
gsutil cp bucket to local crash

### ISSUE THREAD

**Issue by atlanteh** [GoogleCloudPlatform/gsutil#592]
I'm trying to run the following command:
`gsutil cp -r gs://<my-bucket>/<my-path>/photos .`
It's failing, and here's the debug output:
```
Copying gs://<my-bucket>/<my-path>/photos/1545577890412-698.jpeg...
Downloading to temp gzip filename .\1545577890412-698.jpeg_.gztmp
ServiceException: Transfer invalid (possible encoding error: Cannot have start index greater than total size)
```
Windows 10
Google Cloud SDK 228.0.0
bq 2.0.39
core 2018.12.07
gsutil 4.34

I uninstalled GoogleCloudSDK and reinstalled latest yet still the same failure.

**Comment by houglum** [comment]
I believe this was fixed in the latest release, v4.35, via these commits:

https://github.com/google/apitools/commit/8e836fe2942e74d4f6ae5d4b3ccbaf161b9c052b
https://github.com/GoogleCloudPlatform/gsutil/commit/19b55f9b7bb8c8daa1124ee17cb72a932475357e

v4.35 is currently available for standalone installations of gsutil (tar.gz/.zip file, or via pip). If you're using gsutil through a Cloud SDK installation, the next release of the SDK (which will include gsutil 4.35) will be in early January.  I'm marking this as closed, but please reopen this if the problem persists even after you've updated to 4.35 :) Cheers!
