### ISSUE TITLE
MacOS gsutil does not have the compiled crcmod

### ISSUE THREAD

**Issue by elpdumont** [GoogleCloudPlatform/gsutil#604]
`gsutil version -l` leads to `compiled crcmod: False` on my MacOS Mojave. I tried installing crcmod using `sudo pip install -U crcmod` (yes, pip and Xcode were installed) and it says that "Requirement already up-to-date" but it did not fix the issue. I also tried to update gsutil but it did not work. The current version of gsutil is 4.35.

So now, I am unable to donwload large files from the bucket. Have you run into this issue?

Thank you

**Comment by walkerjoe** [comment]
Emmanuel,

Please confirm which version of python you are using. Also, try to run `python -m crcmod.test`. It should show if the installed package is using the compiled binary or not (aka "Using extension").

Thanks,

Joe Walker

**Comment by elpdumont** [comment]
Hi Joe,

Python version is 2.7.15. 

When I run the command you suggest, I obtained the following:
```
Using extension: False

.........
----------------------------------------------------------------------
Ran 9 tests in 0.067s

OK
```
Do you advise updating Python?

**Comment by walkerjoe** [comment]
Emmanuel,

Unfortunately, crcmod shows that it is not using the extension on your installation which is why gsutil is also showing the same issue. There might be a compatibility issue during the installation process of crcmod with the current configuration of your system. I am currently running High Sierra and on my install, crcmod is using the extension and is installed with Python 2.7. However, I do not have a Mojave system to test OS compatibility at this time. 

As far as updating python, we are at a transition point currently where we are still working on python 3 compatibility, so at this time, I do not suggest updating python. I apologize that I could not be of more help on this issue.

**Comment by elpdumont** [comment]
Thanks, Joe, for looking into it. I'll post here if I find a way to make it work on Mojave.

**Comment by cristipp** [comment]
Thanks for the thorough repro explanations. I'm having the same problem as Emmanuel. I've fixed it by manually building crcmod, after patching my MacOS. It appears the root cause is the deprecation of libgcc on XCode 10. Without patching I get the error:

```
gcc -bundle -undefined dynamic_lookup -L/Users/cristipp/miniconda3/envs/gsutil/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/python2/src/_crcfunext.o -L/Users/cristipp/miniconda3/envs/gsutil/lib -o build/lib.macosx-10.5-x86_64-2.7/crcmod/_crcfunext.so
ld: library not found for -lgcc_s.10.5
```

Workaround recipe:
```
$ sudo ln -s /usr/lib/libSystem.B.dylib /usr/local/lib/libgcc_s.10.5.dylib
$ curl -L -o crcmod.tar.gz "https://downloads.sourceforge.net/project/crcmod/crcmod/crcmod-1.7/crcmod-1.7.tar.gz"
$ tar -xzf crcmod.tar.gz
$ cd crcmod-1.7/
$ python setup.py install
$ python -m crcmod.test
Using extension: True

.........
----------------------------------------------------------------------
Ran 9 tests in 0.092s

OK
```

References:
https://github.com/metanorma/homebrew-metanorma/issues/4#issuecomment-456271176
https://stackoverflow.com/a/44160354
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes

**Comment by ethanyanjiali** [comment]
@cristipp thanks for the solution

in my case, i need to change `python setup.py install` to `python setup.py install --user` to have `python -m crcmod.test` display `Using extension: True`

**Comment by nroose** [comment]
I am on Python 3.8 and the above solutions run fine but don't result in the test output saying true for using extension.
