### ISSUE TITLE
Gsutil suddenly stoped to work

### ISSUE THREAD

**Issue by rupestre-campos** [GoogleCloudPlatform/gsutil#817]
I got 
first I was running the .py script directly and suddenly start to get
ServiceException: 401 Anonymous caller does not have storage.objects.get access to gcp-public-data-landsat/LC08/01/232/067/LC08_L1TP_232067_20150411_20170410_01_T1.
CommandException: 1 file/object could not be transferred.

then after trying to update the entire sdk and calling same url via cmd gsutil from path I get now:
AccessDeniedException: 403 Access Not Configured. Please go to the Google Cloud Platform Console (https://cloud.google.com/console#/project) for your project, select APIs and Auth and enable the Google Cloud Storage JSON API.
CommandException: 1 file/object could not be transferred.

all was running normal until now.

**Comment by houglum** [comment]
Hi,

If you think this is a bug in the code, please provide some repro steps and point us to what you think the issue might be.  If you just need support with an error you started getting back from the service, a more appropriate place to post your question is StackOverflow.  Given that this looks like more of a support-type question, rather than a bug in gsutil code, I'm going to mark this issue as closed.

**Comment by rupestre-campos** [comment]
I could manage to make it work by not downloading as anonymos, rather as a real project.
