### ISSUE TITLE
Can't gsutil rewrite storage class with uniform bucket-level access: "No OWNER permission found"

### ISSUE THREAD

**Issue by mhansen** [GoogleCloudPlatform/gsutil#980]
Hey there, I'm trying to move some objects from `STANDARD` to `NEARLINE` storage. `gsutil rewrite` should support this, but I get this error:

```
$ gsutil rewrite -s NEARLINE gs://nz-wireless-map/prism.csv/\*\*
CommandException: No OWNER permission found for object gs://nz-wireless-map/prism.csv/2020-02-02T22:48:03Z. OWNER permission is required for rewriting objects, (otherwise their ACLs would be reset).
```

I think the problem is in [rewrite.py](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/commands/rewrite.py#L390), which errors if we don't have a `src_metadata.acl`:

```
    elif not src_metadata.acl:
      raise CommandException(
          'No OWNER permission found for object %s. OWNER permission is '
          'required for rewriting objects, (otherwise their ACLs would be '
          'reset).' % transform_url)
```

I think my bucket doesn't have an ACL (or at least a legacy ACL): 

```
$ gsutil acl get gs://nz-wireless-map/prism.csv/2020-02-02T22:48:03Z
BadRequestException: 400 Cannot get legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access.
```

My request is to be able to run `gsutil rewrite` on my bucket with uniform bucket-level access. I think this will affect all new buckets - it seems like the ACL is legacy, so it seems likely that `gsutil rewrite` isn't working for any new buckets.

**Comment by thomasmaclean** [comment]
The `-O` option will turn off ACL management which is exactly what you want when your bucket has uniform bucket-level access (UBLA) turned on as it means there are no ACL's to manage! There are 2 possible solutions in this case:

1. get the bucket metadata to determine whether the object is in a UBLA bucket prior to the check for `src_metadata.acl`
2. inform the user to use the `-O` option in both the `rewrite` command documentation and in the `No OWNER permission found...` message in cases where their bucket has UBLA turned on.

I personally prefer option 2 since it doesn't involve a bucket get call which may fail in cases where the user lacks bucket permissions.

**Comment by mhansen** [comment]
Thank you!
